//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRXpense.App.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryAllowances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryAllowances()
        {
            this.TravelReports = new HashSet<TravelReports>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public decimal Amount { get; set; }
        public string AllowanceCurrency { get; set; }
        public string OfficialCurrency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelReports> TravelReports { get; set; }
    }
}
