//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRXpense.App.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string BillNumber { get; set; }
        public decimal BillAmount { get; set; }
        public int ExpenseCategoryId { get; set; }
        public int TravelReportId { get; set; }
        public string Currency { get; set; }
    
        public virtual ExpenseCategories ExpenseCategories { get; set; }
        public virtual TravelReports TravelReports { get; set; }
    }
}
