//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRXpense.App.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelReports()
        {
            this.Expenses = new HashSet<Expenses>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string EmployeeId { get; set; }
        public int CountryAllowanceId { get; set; }
        public string City { get; set; }
        public int VehicleType { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string ReasonForTravel { get; set; }
        public System.DateTime Departure { get; set; }
        public System.DateTime Return { get; set; }
        public decimal ExpenseSum { get; set; }
        public int Status { get; set; }
        public double NumberOfHours { get; set; }
        public double NumberOfAllowances { get; set; }
        public Nullable<decimal> StartMileage { get; set; }
        public Nullable<decimal> EndMileage { get; set; }
        public int NumberOfMeals { get; set; }
        public bool Deposit { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CountryAllowances CountryAllowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenses> Expenses { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
